# generate_text_file.py

def main():
    filename = "for_test.txt"
    content = [
        "Hello, world!",
        "This is a text file generated by Python.",
        "Each line is written programmatically."
    ]

    with open(filename, "w") as f:
        for line in content:
            f.write(line + "\n")

    print(f"File '{filename}' has been created successfully!")

if __name__ == "__main__":
    main()
